[pytest]
testpaths = testcases
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: 冒烟用例（核心主流程）
    api: 接口自动化用例
    ui: WebUI 自动化用例
addopts = -v
log_cli = false
